version: "3.7"

networks: 
  db-net:
    driver: bridge

services:
  db:
    build: ./image-postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes: 
      - ./postgres:/bitnami/postgresql
    networks: 
      - db-net
    restart: "on-failure"

  web:
    build: ./
    env_file: .env
    ports:
      - 9000:9000
    networks: 
      - db-net
    depends_on:
      - db
    restart: "on-failure"
